theme: jekyll-theme-minimal
title: Carlos González Bueno
description: "Official website and professional portfolio of Carlos González Bueno."
url: "https://carloszip.github.io"
plugins:
  - jekyll-sitemap